name = input("Enter ur name:")
city = input("Enter ur city:")
fav_food = input("Enter ur fav food:")
fav_animal = input("Enter ur fav animal:")
fav_color = input("Enter ur fav color:")
fav_actor = input("Enter ur fav actor:")
fav_person = input("Enter ur fav person:")
fav_actress = input("Enter ur fav actress:")
fav_movie = input("Enter ur fav_movie:")
fav_singer = input("Enter ur fav singer:")

print("!!!!INFO!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_animal=}')
print(f'{fav_color=}')
print(f'{fav_actor=}')
print(f'{fav_person=}')
print(f'{fav_actress=}')
print(f'{fav_movie=}')
print(f'{fav_singer=}')


